export const activities = {
    'Izjašnjavanje učenika iz kog predmeta će raditi treći test.' : new Date('Dec 31, 2022').getTime(),
    'Provera tačnosti izjašnjenja iz kog predmeta će učenici raditi treći test.': new Date('Jan 27, 2023').getTime(),
    'Promena odluke o trećem testu.': new Date('Jan 31, 2023 15:00:00').getTime(),
    'Objavljivanje konačnog izjašnjenja učenika o trećem testu.': new Date('Feb 1, 2023 08:00:00').getTime(),
    'Probni završni ispit - matematika': new Date('Mart 24, 2023 12:00:00').getTime(),
    'Probni završni ispit - srpski jezik i treći test': new Date('Mart 25, 2023 09:00:00').getTime(),
    'Analiza probnog završnog ispita': new Date('Mart 31, 2023').getTime(),
    'Elektronsko i neposredno prijavljivanje kandidata za prijemni ispit.': new Date('April 24, 2023 16:00:00').getTime(),
    'Prijemni ispiti u umetničkim školama likovne oblasti.': new Date('May 12, 2023').getTime(),
    'Prijemni ispit za učenike sa posebnim sposobnostima za biologiju i hemiju.': new Date('May 13, 2023').getTime(),
    'Prijemni ispit za učenike sa posebnim sposobnostima za scenske i audio-vizuelne umetnosti.': new Date('May 13, 2023').getTime(),
    'Prijemni ispit za učenike sa posebnim sposobnostima za filološke nauke.': new Date('May 14, 2023').getTime(),
    'Prijemni ispit za učenike sa posebnim sposobnostima za računarstvo i informatiku i fiziku (matematika).': new Date('May 20, 2023').getTime(),
    'Prijemni ispit za učenike sa posebnim sposobnostima za geografiju i istoriju.': new Date('May 20, 2023').getTime(),
    'Prijemni ispit za učenike sa posebnim sposobnostima za fiziku.': new Date('May 20, 2023').getTime(),
    'Prijemni ispit za odeljenja u kojima se nastava ostvaruje na stranom jeziku.': new Date('May 20, 2023').getTime(),
    'Prijemni ispit u muzičkim školama.': new Date('May 21, 2023').getTime(),
    'Prijemni ispit u baletskim školama.': new Date('May 21, 2023').getTime(),
    'Prijemni ispit za učenike sa posebnim sposobnostima za matematiku.': new Date('May 21, 2023 10:00:00').getTime(),
    'Preliminarni rezultati prijemnih ispita.': new Date('May 23, 2023').getTime(),
    'Podnošenje i rešavanje prigovora na preliminarne rezultate prijemnih ispita.': new Date('May 23, 2023').getTime(),
    'Konačni rezultati prijemnih ispita.': new Date('May 24, 2023').getTime(),
    'Prijavljivanje učenika i podnošenje sportske dokumentacije za Sportsku gimnaziju i sportska odeljenja pri ostalim gimnazijama.': new Date('Jun 10, 2023').getTime(),
    'Prijemni ispit za IBO odeljenja u gimnazijama.': new Date('Jun 17, 2023').getTime(),
    'Završni ispit - srpski jezik': new Date('Jun 21, 2023 09:00:00').getTime(),
    'Završni ispit - matematika': new Date('Jun 22, 2023 09:00:00').getTime(),
    'Završni ispit - treći test': new Date('Jun 23, 2023 09:00:00').getTime(),
    'Preliminarni rezultati završnog ispita.': new Date('Jun 25, 2023').getTime(),
    'Elektronski prigovori na preliminarne rezultate završnog ispita.': new Date('Jun 25, 2023').getTime(),
    'Prigovori na preliminarne rezultate završnog ispita - neposredno u školi.': new Date('Jun 26, 2023').getTime(),
    'Dostavljanje odgovora prvostepene komisije na prigovore.': new Date('Jun 27, 2023').getTime(),
    'Prigovori za drugostepenu komisiju.': new Date('Jun 27, 2023').getTime(),
    'Dostavljanje odgovora drugostepene komisije na prigovore.': new Date('Jun 27, 2023 16:00:00').getTime(),
    'Objavljivanje konačnih rezultata završnog ispita.': new Date('Jun 28, 2023 08:00:00').getTime(),
    'Upis u muzičke i baletske škole.': new Date('Jun 28, 2023 15:00:00').getTime(),
    'Elektronsko popunjavanje liste želja.': new Date('Jun 29, 2023 08:00:00').getTime(),
    'Popunjavanje liste želja neposredno u školi.': new Date('Jun 30, 2023 08:00:00').getTime(),
    'Prigovori na liste želja i unošenje ispravki.': new Date('Jul 1, 2023 08:00:00').getTime(),
    'Objavljivanje konačne liste želja učenika.': new Date('Jul 2, 2023 08:00:00').getTime(),
    'Objavljivanje konačnih rezultata raspodele po školama i obrazovnim profilima.': new Date('Jul 3, 2023').getTime(),
    'Objavljivanje preostalih slobodnih mesta za upis u drugom upisnom krugu.': new Date('Jul 3, 2023').getTime(),
    'Popunjavanje liste želja za drugi upisni krug.': new Date('Jul 3, 2023').getTime(),
    'Neposredno podnošenje prijave za upis učenika u srednje škole, osim za muzičke i baletske škole.': new Date('Jul 3, 2023').getTime(),
    'Objavljivanje konačnog rasporeda učenika po školama u drugom upisnom krugu.': new Date('Jul 4, 2023 23:59:00').getTime(),
    'Objavljivanje preostalih slobodnih mesta za upis posle drugog upisnog kruga.': new Date('Jul 5, 2023 08:00:00').getTime(),
    'Podnošenje prijave za upis u srednje škole za drugi upisni krug, osim za muzičke i baletske škole.': new Date('Jul 5, 2023 15:00:00').getTime(),
    'Elektronsko podnošenje prijave za upis učenika u srednje škole posle prvog i drugog upisnog kruga.': new Date('Jul 7, 2023 15:00:00').getTime(),
    'Završni ispit - avgustovski rok - srpski jezik': new Date('Aug 16, 2023').getTime(),
    'Završni ispit - avgustovski rok - matematika': new Date('Aug 17, 2023').getTime(),
    'Završni ispit - avgustovski rok - treći test': new Date('Aug 18, 2023').getTime(),
    'Preliminarni rezultati avgustovskog završnog ispita na nivou škole.': new Date('Aug 21, 2023').getTime(),
    'Prigovori na rezultate avgustovskog završnog ispita i podnošenje molbi za upis (u okružnim upisnim komisijama).': new Date('Aug 22, 2023').getTime(),
    'Unos odluka o upisu.': new Date('Aug 23, 2023').getTime(),
    'Upis učenika u srednje škole - treći upisni krug, osim za muzičke i baletske škole.': new Date('Aug 24, 2023').getTime(),
    'Prijavljivanje i raspoređivanje vanrednih učenika starijih od 17 godina za upis u srednju školu.': new Date('Aug 25, 2023').getTime()
}